### ISSUE TITLE
Sandbox implementation is flawed

### ISSUE THREAD

**Issue by stof** [videlalvaro/RabbitMqBundle#148]
Currently, turning on the sandbox mode in the config (which seems meaningful for a test environment) is likely to break the code with a Fatal error (it would in my app for instance).

The behavior of this option is to switch producer services from the [Producer](https://github.com/videlalvaro/RabbitMqBundle/blob/master/RabbitMq/Producer.php) class to the [Fallback](https://github.com/videlalvaro/RabbitMqBundle/blob/master/RabbitMq/Fallback.php).
But the Fallback class does not extend Producer, which means it will not pass the typehints

**Comment by mbiagetti** [comment]
:+1:

**Comment by videlalvaro** [comment]
can this issue be closed now?
