### ISSUE TITLE
Provide a way to reject message and exit consumer

### ISSUE THREAD

**Issue by greg0ire** [videlalvaro/RabbitMqBundle#180]
I have a Consumer that uses Doctrine2. When a doctrine error occurs, the entity manager gets closed and usable. Rebuilding this object is very cumbersome. The simplest way to move on would be to simply restart the consumer. Is there a way to achieve this ? For the moment, I do this at the top of my script:

```php
if (!$this->em->isOpen()) {
     $this->logger->err('The entity manager is closed. Exiting.');
     exit(1);
 }
```

By doing this, the consumer exits when receiving a (probably fine) message *after* the message that caused the error, supervisord restarts it because it sees the status is not 0 or 2 (supervisord default `exitcodes` setting value), and the fine message is processed again. All is well, but I think there could be a `ConsumerInterface` constant to state "reject message and exit with 1". That would be cleaner.

**Comment by greg0ire** [comment]
@bburnichon : sorry but I'm having a hard time figuring out how to solve this using your work. Can you please help?

**Comment by bburnichon** [comment]
@greg0ire You can use `$this->dequeuer->forceStopConsumer()` to indicate that the current consumer stalled and will not accept to process further messages. The consumer will process current Message normally. You can return any const from `ConsumerInterface`.

In your case: 
```php
if (! $this->em->isOpen()) {
  $this->dequeuer->forceStopConsumer();
  return ConsumerInterface::MSG_REJECT_REQUEUE;
}
```

If you want to process a message normally but for example, want to avoid memory leaks in doctrine extensions (this was my use case), you can do:

```php
// Your process
$this->dequeuer->forceStopConsumer();

return ConsumerInterface::MSG_ACK;
```

Your message will be removed from the queue and acknowledged. Your consumer will exit normally with an `exit(0);`

**Comment by greg0ire** [comment]
Thanks a lot for the detailed answer, I'll do as you said.
