### ISSUE TITLE
Connexion Refused

### ISSUE THREAD

**Issue by Steven-Sanseau** [videlalvaro/RabbitMqBundle#225]
Hi,
It's possible to use this bundle when RabbitMq is unload ?
For Multiple reasons, i need use my app every time and if Rabbitmq downtime, my app crash too. 
Thanx for answer

**Comment by videlalvaro** [comment]
If RabbitMQ is under load then it will refuse connections, also there are many reasons why this would happen. I would suggest you post a question with more details here: https://groups.google.com/forum/#!forum/rabbitmq-users
