### ISSUE TITLE
Configuring ssl_context leads to container dump errors.

### ISSUE THREAD

**Issue by marco-jantke** [videlalvaro/RabbitMqBundle#232]
As soon as I add ssl_context options to a connection configuration, Symfony fails when dumping the the container configuration.

This happens because the context parameter for the ampq connection service is of type resource, what is not supported by Symfony. 

Anyone has a clue how to solve that issue?

    user@host:/var/www/vhost$ php app/console rabbitmq:consumer -l 256 consumer_name -vvv --env=dev
                                                                                     
      [Symfony\Component\DependencyInjection\Exception\RuntimeException]             
      Unable to dump a service container if a parameter is an object or a resource.  

    Exception trace:
     () at /var/www/emergency-system/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php:332
     Symfony\Component\DependencyInjection\Dumper\XmlDumper::phpToXml() at /var/www/emergency-system/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php:281
     Symfony\Component\DependencyInjection\Dumper\XmlDumper->convertParameters() at /var/www/emergency-system/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php:170
     Symfony\Component\DependencyInjection\Dumper\XmlDumper->addService() at /var/www/emergency-system/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php:225
     Symfony\Component\DependencyInjection\Dumper\XmlDumper->addServices() at /var/www/emergency-system/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php:56
     Symfony\Component\DependencyInjection\Dumper\XmlDumper->dump() at /var/www/emergency-system/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ContainerBuilderDebugDumpPass.php:34
     Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\ContainerBuilderDebugDumpPass->process() at /var/www/emergency-system/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:117
     Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /var/www/emergency-system/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:612
     Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /var/www/emergency-system/app/bootstrap.php.cache:2548
     Symfony\Component\HttpKernel\Kernel->initializeContainer() at /var/www/emergency-system/app/bootstrap.php.cache:2327
     Symfony\Component\HttpKernel\Kernel->boot() at /var/www/emergency-system/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:70
     Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/emergency-system/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
     Symfony\Component\Console\Application->run() at /var/www/emergency-system/app/console:27

**Comment by stof** [comment]
The issue is that ``stream_context_create`` returns a resource. So using it in the DI extension to build the service argument is wrong: https://github.com/videlalvaro/RabbitMqBundle/blob/bb2701dbe869543f2cc6a551bd3a1e734c46797e/DependencyInjection/OldSoundRabbitMqExtension.php#L77
The resource needs to be created at runtime, not at build time

**Comment by videlalvaro** [comment]
ping @bburnichon

**Comment by bburnichon** [comment]
hum. This can be solved with an `Symfony\Component\ExpressionLanguage\Expression` but only for symfony versions above 2.4.

I should take time to create a connection factory service.

**Comment by stof** [comment]
Actually, it can only be solved using expressions for 2.6.2+, because you would need to register a custom function in the DI expression language, which is not possible previously (not possible in 2.4 and 2.5 and buggy in 2.6.0 and 2.6.1)
