### ISSUE TITLE
[Feature] --queue option for rabbitmq:consumer command

### ISSUE THREAD

**Issue by tiborb** [videlalvaro/RabbitMqBundle#250]
In some situations it would be handy to if the queue name could be specified from the CLI, e.g. creating more dynamic consumers.

The queue name for a consumer is now optional, so Rabbit generates a name for you if you leave it blank in the consumers config, so we might as well add an option similar to --route.

Usage would be:
rabbitmq:consumer [-m|--messages[="..."]] **[-q|--queue[="..."]]** [-r|--route[="..."]] [-l|--memory-limit[="..."]] [-d|--debug] [-w|--without-signals] name

[...]
--queue(-r)           Queue (default: "")
[...]

I could implement this feature.
Cheers.

**Comment by videlalvaro** [comment]
Cool, please just make sure the `queue` option doesn't conflict with an existing one
