### ISSUE TITLE
[Question] RabbitMqBundle + logger

### ISSUE THREAD

**Issue by tiborb** [videlalvaro/RabbitMqBundle#255]
Hello, 

Here's the scenario:
I have a callback (service) in symfony2 in which I inject the logger.
The logger (Monolog\Handler\FingersCrossedHandler) buffers every line and causing an increased memory usage for every processed message.
It seems like Symfony2 and logging it not designed for long running processes.

So my question is: what kind of logger are you using for the rabbitMqBundle consumers?

Thank you,
Tibor

**Comment by notFloran** [comment]
Hi,

You can use a StreamHandler or ConsoleHandler in this case.

Floran

**Comment by videlalvaro** [comment]
Is this the same as this SO question? Are the answers there or the one by @notFloran correct? If yes please close this issue

**Comment by tiborb** [comment]
Yes, the question has been answered. Thanks
