### ISSUE TITLE
Tagging latest version

### ISSUE THREAD

**Issue by jasonroman** [videlalvaro/RabbitMqBundle#262]
There have been many commits since the latest 1.6.0 tag in January, including some fixes for PHP version 5.3.  Can this be tagged as 1.6.1 or 1.7.0?  Right now I have to use dev-master in my composer dependencies.  When that dependency is solely in a Symfony bundle it doesn't get picked up because of minimum-stability settings for our application.

**Comment by videlalvaro** [comment]
https://github.com/videlalvaro/RabbitMqBundle/releases/tag/v1.7.0
