### ISSUE TITLE
[Feature] Resequencer

### ISSUE THREAD

**Issue by tiborb** [videlalvaro/RabbitMqBundle#270]
Hi, 

has anybody tried to implement a resequencer using rabbitmq+php as stated here: http://www.enterpriseintegrationpatterns.com/Resequencer.html

It could be a nice addition to the bundle too.
I would be willing to implement it as soon as I find a solution.

Suggestions?

Cheers,
Tibor

**Comment by videlalvaro** [comment]
I don't know of any Resequencer in PHP.

**Comment by tiborb** [comment]
Thanks, I am currently experimenting with my own implementation, will update as soon as I have a working prototype.

**Comment by tiborb** [comment]
I have an experimental resequencer which looks for a gap in the sequence and keeps unordered messages in a buffer until the sequence is complete.
The only problem is that the buffer should timeout if the stored messaged could not be ordered, but PHP is not evented. So there is no flush trigger event. In theory only the next message could trigger a flush.

https://github.com/tiborb/resequencer

**Comment by tiborb** [comment]
It seems that at least 2 workers are needed in the php world, one as a resequencer, one to flush the buffer (shared memory, redis) from time to time. This is not really practical in the bundle so i will close this issue.
