### ISSUE TITLE
Unclear documentation: how to return rpc message

### ISSUE THREAD

**Issue by Napas** [videlalvaro/RabbitMqBundle#275]
I've implemented RPC server service which implements ConsumerInterface.

How message to client should be returned?

**Comment by videlalvaro** [comment]
Did you see this part of the README?

```php 
public function indexAction($name)
{
    $client = $this->get('old_sound_rabbit_mq.integer_store_rpc');
    $client->addRequest(serialize(array('min' => 0, 'max' => 10)), 'random_int', 'request_id');
    $replies = $client->getReplies();
}
```

Specifically `$client->getReplies();` ?

https://github.com/videlalvaro/RabbitMqBundle#rpc-or-replyresponse

**Comment by Napas** [comment]
Yes, but this is from client side.

I am implementing server in different Symfony2 app.

In config I have:

    rpc_servers:
        hadoop:
            connection:       default
            callback:         consumer.hadoop
            qos_options:      { prefetch_size: 0, prefetch_count: 1, global: false }
            exchange_options: { name: hadoop, type: direct }
            queue_options:    { name: hadoop, durable: false, auto_delete: true }
            serializer:       json_encode

consumer.hadoop service implements ConsumerInterface. In which I got message, other stuff gets done and then I need to send response back to other app from which message was sent.

It seems there are no documentation how to implement server or am I missing something?

**Comment by videlalvaro** [comment]
your callback will receive an AMQPMessage if I'm not mistaken. From that message you can access the current `$channel`. Use that channel to `basic_publish` a message to whatever destination comes next on your pipeline.

**Comment by Napas** [comment]
Thanks!
