### ISSUE TITLE
dynamic queue and routing key

### ISSUE THREAD

**Issue by pinouf** [videlalvaro/RabbitMqBundle#278]
hello,

i would like to create on a fly a process consumer who listen on a queue and a routing key.

By example,
I send i request to a server . the server response me with a queue and a routing key 
and i create a consumer to get message which is on this  queue and on this routing key.

How can i configure that? Or if it is not possible, how can i instantiate a object Consumer with this parameter?

thank you,
Best regards,

**Comment by Padam87** [comment]
This looks like a very weird use case for a message queue, but if you really want to do it like this I think you can just skip the configuration part and create the consumer on the fly.

**Comment by pinouf** [comment]
Thank you @Padam87, indeed it is a weird use case -) .
I can't wait the 1.7 but it is not important because  i resolved my problem.

i managed to make a command who take 3 params ( exchangeName, queueName, routingKey ) which allow to the client to initiate a consumer and get severals message.
When i get the last message , i destruct the consumer and the queueName -)
