### ISSUE TITLE
High memory usage when producing messages

### ISSUE THREAD

**Issue by mrbase** [videlalvaro/RabbitMqBundle#296]
I found that when producing messages in a loop the script uses quite a bit of memory.

The loop generates ~376.000 messages of ~1.200 bytes each. The memory used for this is close to 1GB - which seams like a lot to me.

The producer is made as a `command` and is executed with the `--env=prod` and `--no-debug` flags.

I have generated a [blackfire profile](https://blackfire.io/profiles/550ad26c-988f-430d-876f-7146c0436b48/graph) which might give some pointers.

From what I can tell, the `PhpAmqpLib\Wire\GenericContent::serialize_properties` uses 90% of that memory.

My producer code is quite simple:
- setting content type
- publish a json_encoded message
- no routing key
- no additional properties

The reason I created this issue was that we planned to produce many more jobs in loops like this, but with so high a memory usage ... So I just wanted to find out weather this is normal/expected or not .?

**Comment by videlalvaro** [comment]
I would assume that PHP generates a lot of garbage when instantiating many classes inside a loop.

If you want to debug this and send a PR to php-amqplib, it would be really great

**Comment by mrbase** [comment]
Will do, closing here and opening a new one in php-amqplib.
