### ISSUE TITLE
Producer->publish() inside Consumer execute() stops message from being ACKed

### ISSUE THREAD

**Issue by reinierbutot** [videlalvaro/RabbitMqBundle#318]
When I inject a producer inside my consumer and publish a message inside the execute() method of my consumer, the consumer does not ACK the message it was consuming.

Not sure why, since publishing a message does not return FALSE.
And even when returning TRUE after the message has been published, it does not ACK the message.

Only code in execute() of my consumer:

    $this->producer->publish($message->body);
    return true;

Also, when a FALSE is returned, more messages get added to the original queue the message I am trying to consume comes from.

**Comment by videlalvaro** [comment]
I think you have to get the channel from the message passed here: https://github.com/videlalvaro/RabbitMqBundle/blob/master/RabbitMq/ConsumerInterface.php#L34 and then publish on that channel.

See here for more info: https://github.com/videlalvaro/php-amqplib/blob/master/doc/AMQPMessage.md

**Comment by reinierbutot** [comment]
Thanks!

Got it to work inside my Consumer execute(), using:

    $message->delivery_info['channel']
        ->basic_publish( new AMQPMessage (serialize($data)), 'name_of_my_exchange', 'key.of.my.routing' );
